name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm ci

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      # Add test step when you have tests
      # - name: Test
      #   run: pnpm test

      - name: Build Storybook
        run: pnpm run build-storybook
